spring:
    profiles: test
#YamlConfig.java
name: test-YAML
environment: test
servers:
    - www.abc.test.com
    - www.xyz.test.com
#YAMLSupportedRoleTemplatesProperties.java
ldap:
  username: test.user
  supportedRoleTemplates: [AdminTest, SupportOperatorTest]
---
spring:
    profiles: default
#YamlConfig.java
name: prod-YAML
environment: production
servers:
    - www.abc.com
    - www.xyz.com
#YAMLSupportedRoleTemplatesProperties.java
ldap:
  username: production.user
  supportedRoleTemplates:
    - Admin
    - SupportOperator
    - FraudOperator
    - TechSigner
    - SystemMigration